### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by shivateja9090** [dhhruv/todo#1]
hey in upload what files we should upload

**Comment by dhhruv** [comment]
You have been provided a Starter Repo for 5 languages. Download anyone (depends on your preference of language), unzip it, make changes in the files as needed and then zip the folder using WinZip/WinRar/7-zip and upload the ".zip" file.

**Comment by SNJV229** [comment]
![image](https://user-images.githubusercontent.com/38901682/102468605-bfe9f980-4077-11eb-8948-3a0a7dbf1f65.png)
bro i am getting this error do yo  know what is the reason behind this error?? While testing...

**Comment by dhhruv** [comment]
> ![image](https://user-images.githubusercontent.com/38901682/102468605-bfe9f980-4077-11eb-8948-3a0a7dbf1f65.png)
> bro i am getting this error do yo know what is the reason behind this error?? While testing...

You've to install Node.js from [https://nodejs.org/en/](https://nodejs.org/en/) and install jest using `npm install jest` from your command line and then you can run the command you shown in your image.

**Comment by sivas36** [comment]
![Screenshot (208)](https://user-images.githubusercontent.com/67056444/102596310-ff2f4d80-413e-11eb-93a8-f3996b947689.png)
![Screenshot (208)](https://user-images.githubusercontent.com/67056444/102596367-140be100-413f-11eb-8177-7e9420c8729e.png)


         i got this error while testing?can u pls help me out

**Comment by sivas36** [comment]
![Screenshot (209)](https://user-images.githubusercontent.com/67056444/102597647-fb9cc600-4140-11eb-8007-f9725241e428.png)
bro i got error here can u pls help me out

**Comment by dhhruv** [comment]
> ![Screenshot (209)](https://user-images.githubusercontent.com/67056444/102597647-fb9cc600-4140-11eb-8007-f9725241e428.png)
> bro i got error here can u pls help me out

Re-download node modules and run again. Don't change anything in todo.test.js file.

**Comment by SudharshanK-10** [comment]
Bro I'm getting this error in c++. At the end of each cout line, my output has somethin like a dot, but in my code there isn't anythin like that, any idea on how to fix it
<img width="421" alt="Screenshot 2020-12-18 165159" src="https://user-images.githubusercontent.com/76208976/102609592-c3ea4a00-4151-11eb-9626-b80f1c2616e1.png">
<img width="585" alt="Screenshot 2020-12-18 165103" src="https://user-images.githubusercontent.com/76208976/102609672-e67c6300-4151-11eb-84e8-3bf541615138.png">

?
