### ISSUE TITLE
Doubt !

### ISSUE THREAD

**Issue by SudharshanK-10** [dhhruv/todo#2]
Bro I'm getting this error in c++. At the end of each cout line, my output has somethin like a dot, but in my code there isn't anythin like that, any idea on how to fix it ?
<img width="370" alt="Screenshot 2020-12-18 170622" src="https://user-images.githubusercontent.com/76208976/102610661-969e9b80-4153-11eb-8750-825cfd1c677e.png">
<img width="611" alt="Screenshot 2020-12-18 170541" src="https://user-images.githubusercontent.com/76208976/102610664-97373200-4153-11eb-83b3-6a8b841662bb.png">

**Comment by dhhruv** [comment]
> Bro I'm getting this error in c++. At the end of each cout line, my output has somethin like a dot, but in my code there isn't anythin like that, any idea on how to fix it ?
> <img alt="Screenshot 2020-12-18 170622" width="370" src="https://user-images.githubusercontent.com/76208976/102610661-969e9b80-4153-11eb-8750-825cfd1c677e.png">
> <img alt="Screenshot 2020-12-18 170541" width="611" src="https://user-images.githubusercontent.com/76208976/102610664-97373200-4153-11eb-83b3-6a8b841662bb.png">

Try to convert it into UTF-8 encoding while buffering in the output.
